web:
  container_name: web
  build: .
  ports:
    - "5000:9000"
  volumes:
    - ./gopath:/myproject/gopath
    - ./golang:/myproject/golang
  working_dir: "/myproject/gopath/src/gozen"
  links:
    - db
  tty: true

db:
  container_name: db
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: gozen
    MYSQL_USER: gozen
    MYSQL_PASSWORD: rootpass
  volumes:
    - ./mysql:/etc/mysql/conf.d
    - /var/lib/mysql
