web:
  container_name: web
  image: golang:1.7.3
  ports:
    - "5000:9000"
  volumes:
    - ./:/go/src/gozen
  working_dir: "/go/src/gozen"
  links:
    - db
  tty: true
  command: /bin/bash

db:
  container_name: db
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: gozen
    MYSQL_USER: gozen
    MYSQL_PASSWORD: rootpass
  volumes:
    - ./mysql:/etc/mysql/conf.d
    - /var/lib/mysql


